
package br.com.senac.jnaliancas.gui.buscar;

import br.com.senac.jnaliancas.dao.AgendamentoDAO;
import br.com.senac.jnaliancas.dao.ClienteDAO;
import br.com.senac.jnaliancas.dao.EntregaDAO;
import br.com.senac.jnaliancas.dao.PagamentoDAO;
import br.com.senac.jnaliancas.dao.PedidoDAO;
import br.com.senac.jnaliancas.dao.ProdutoDAO;
import br.com.senac.jnaliancas.model.Agendamento;
import br.com.senac.jnaliancas.model.Cliente;
import br.com.senac.jnaliancas.model.Entrega;
import br.com.senac.jnaliancas.model.Pagamento;
import br.com.senac.jnaliancas.model.Pedido;
import br.com.senac.jnaliancas.model.Produto;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Busca extends javax.swing.JFrame {

    private JFrame telaAnterior; 
    private String cargo;
    
    public Busca(JFrame telaAnterior) {
        initComponents();
        this.telaAnterior = telaAnterior;
        this.cargo = cargo;
        iniciar(cargo);
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cbOpcao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 176, 176));

        jPanel2.setBackground(new java.awt.Color(187, 187, 187));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(29, 29, 29));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(225, 162, 83));
        jLabel1.setText("SISTEMA DE BUSCA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(29, 29, 29));

        jPanel5.setBackground(new java.awt.Color(187, 187, 187));
        jPanel5.setToolTipText("Insira os dados a seguir");

        btnBuscar.setBackground(new java.awt.Color(29, 29, 29));
        btnBuscar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(225, 162, 83));
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Clique para buscar");
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbNome.setBackground(new java.awt.Color(0, 0, 0));
        lbNome.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lbNome.setForeground(new java.awt.Color(51, 51, 51));
        lbNome.setLabelFor(txtNome);
        lbNome.setText("Digite o nome do cliente: ");

        txtNome.setBackground(new java.awt.Color(153, 153, 153));
        txtNome.setToolTipText("Insira o nome ");
        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        cbOpcao.setBackground(new java.awt.Color(153, 153, 153));
        cbOpcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Produto", "Pedido", "Estoque", "Agendamento", "Venda", "Pagamento", "Entrega" }));
        cbOpcao.setToolTipText("Selecione um item");
        cbOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpcaoActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setLabelFor(cbOpcao);
        jLabel4.setText("Selecione o que deseja buscar:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(lbNome)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 136, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnBuscar.getAccessibleContext().setAccessibleDescription("Botão para buscar");
        txtNome.getAccessibleContext().setAccessibleName("Nome");
        txtNome.getAccessibleContext().setAccessibleDescription("Campo para inserção de nome");
        cbOpcao.getAccessibleContext().setAccessibleName("Selecionar item");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(225, 162, 83));
        jLabel3.setText("Informe os dados abaixo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.getAccessibleContext().setAccessibleName("");

        btnSair.setBackground(new java.awt.Color(204, 204, 204));
        btnSair.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(51, 51, 51));
        btnSair.setText("Sair");
        btnSair.setToolTipText("Clique para sair");
        btnSair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 29, 29), 3, true));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(204, 204, 204));
        btnVoltar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(51, 51, 51));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique para voltar");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 29, 29), 3, true));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar(String cargo){
        if(cargo == "Atendente"){
            cbOpcao.removeItem("Estoque");
            cbOpcao.removeItem("Venda");
        }
        
        else if(cargo == "Financeiro"){
            cbOpcao.removeItem("Estoque");
            cbOpcao.removeItem("Cliente");
            cbOpcao.removeItem("Produto");
            cbOpcao.removeItem("Pedido");
            cbOpcao.removeItem("Agendamento");
            cbOpcao.removeItem("Entrega");
        }
    }
    
    private Cliente buscarCliente(){
        ClienteDAO cd = new ClienteDAO();
        for (Cliente c : cd.listar()) {
            if (c.getNome().equalsIgnoreCase(txtNome.getText().trim())) {
                return c;
            }
        }
        return null;
    }
    
    private Pedido buscarPedido(){
        PedidoDAO pd = new PedidoDAO();
        for (Pedido p : pd.listar()) {
            if (p.getCliente().getNome().equalsIgnoreCase(txtNome.getText().trim())) {
                return p;
            }
        }
        return null;
    }
    
    private Agendamento buscarAgendamento(){
        AgendamentoDAO ad = new AgendamentoDAO();
        for (Agendamento a : ad.listar()) {
            if (a.getCliente().getNome().equalsIgnoreCase(txtNome.getText().trim())) {
                return a;
            }
        }
        return null;
    }
    
    private Produto buscarProduto(){
        ProdutoDAO pd = new ProdutoDAO();
        for (Produto p : pd.listar()) {
            if (p.getNome().equalsIgnoreCase(txtNome.getText().trim())) {
                return p;
            }
        }
        return null;
    }
    
    private Pagamento buscarPagamento() {
        PagamentoDAO pd = new PagamentoDAO();
        for (Pagamento p : pd.listar()) {
            if (p.getCliente().getNome().equalsIgnoreCase(txtNome.getText().trim())) {
                return p;
            }
        }
        return null;
    }
    
    private Entrega buscarEntrega() {
        EntregaDAO ed = new EntregaDAO();
        for (Entrega e : ed.listar()) {
            if (e.getCliente().getNome().equalsIgnoreCase(txtNome.getText().trim())) {
                return e;
            }
        }
        return null;
    }
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo deve ser preenchido.");
        }
        else if (!txtNome.getText().trim().matches("^[a-zA-ZÀ-ÿ ]+$")){
            JOptionPane.showMessageDialog(null, "Nome inválido! Digite apenas letras e espaços.");
        }
        else{
             String opcao = cbOpcao.getSelectedItem().toString();
             
             if(opcao.equals("Cliente")){
                 
                 Cliente cliente = buscarCliente();
                 
                 if(cliente == null){
                     JOptionPane.showMessageDialog(null, "Cliente inválido! Pessoa não cadastrada.");
                 }
                 
                 else{
                     JOptionPane.showMessageDialog(null, "Dados do Cliente\nNome: " + cliente.getNome() + "\nIdade: " + cliente.getIdade() + "\nCPF: " + cliente.getCpf() + "\nTelefone: " + cliente.getTelefone() + "\nEndereco: " + "Rua " +  cliente.getRua() + ", nº" + cliente.getNumero() + ", " + cliente.getComplemento() + ", bairro " + cliente.getBairro() + ", " +  cliente.getCidade() + ", " + cliente.getEstado() + ", " + cliente.getCep());
                 }
             }
             
             else if(opcao.equals("Pedido")){
                 
                 Pedido pedido = buscarPedido();

                 if (pedido == null) {
                     JOptionPane.showMessageDialog(null, "Cliente inválido! Pessoa não cadastrada.");
                 }
                 
                 else{
                     JOptionPane.showMessageDialog(null, "Dados do Pedido\nProduto: " + pedido.getProduto().getNome() + "\nCliente: " + pedido.getCliente().getNome() + "\nQuantidade: " + pedido.getQuantidade() + "\nData: " + pedido.getData() + "\nObservações: " + pedido.getObservacoes());
                 }
                 
             }
             
             else if (opcao.equals("Venda")) {

                Pedido pedido = buscarPedido();

                if (pedido == null) {
                    JOptionPane.showMessageDialog(null, "Cliente inválido! Pessoa não cadastrada.");
                } else {
                    JOptionPane.showMessageDialog(null, "Dados da Venda\nCliente: " + pedido.getCliente().getNome() + "\nData: " + pedido.getData() + "\nValor: " + (pedido.getProduto().getPreco() * pedido.getQuantidade()) + "\nProduto: " + pedido.getProduto().getNome());
                }

            }
             
             else if(opcao.equals("Pagamento")){
                 
                 Pagamento pagamento = buscarPagamento();
                 
                 if (pagamento == null) {
                     JOptionPane.showMessageDialog(null, "Cliente inválido! Pessoa não cadastrada.");
                 } else {
                     JOptionPane.showMessageDialog(null, "Dados do Pagamento\nCliente: " + pagamento.getCliente().getNome() + "\nValor total: " + pagamento.getValor() + "\nTipo: " + pagamento.getTipo() + "\nValor pago: " + pagamento.getPago() + "\nValor pendente: " + pagamento.getValorPendente());
                 }
             }
             
             else if(opcao.equals("Entrega")){
                 
                 Entrega entrega = buscarEntrega();
                 
                 if (entrega == null){
                     JOptionPane.showMessageDialog(null, "Cliente inválido! Pessoa não cadastrada.");
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "Dados da Entrega\nTipo: " + entrega.getTipo() + "\nCliente: " + entrega.getCliente().getNome() + "\nEndereço: " + "Rua " +  entrega.getCliente().getRua() + ", nº" + entrega.getCliente().getNumero() + ", " + entrega.getCliente().getComplemento() + ", bairro " + entrega.getCliente().getBairro() + ", " + entrega.getCliente().getCidade() + ", " + entrega.getCliente().getEstado() + ", " + entrega.getCliente().getCep() + "\nFrete: " + entrega.getFrete() + "\nPrazo: " + entrega.getPrazo() + "\nObservações: " + entrega.getObservacoes());
                 }
             }
             
             else if(opcao.equals("Agendamento")){
                 
                 Agendamento agendamento = buscarAgendamento();
                 
                 if(agendamento == null){
                     JOptionPane.showMessageDialog(null, "Cliente inválido! Pessoa não cadastrada.");
                 }
                 
                 else{
                     JOptionPane.showMessageDialog(null, "Dados do Agendamento\nCliente: " + agendamento.getCliente().getNome() + "\nData: " + agendamento.getData() + "\nHora: " + agendamento.getHora() + "\nObservações: " + agendamento.getObservacoes());
                 }
             }
             
             else if(opcao.equals("Produto")){
                 
                 Produto produto = buscarProduto();
                 
                 if(produto == null){
                     JOptionPane.showMessageDialog(null, "Produto inválido! Item não cadastrado.");
                 }
                 
                 else{
                     JOptionPane.showMessageDialog(null, "Dados do Produto\nNome: " + produto.getNome() + "\nMaterial: " + produto.getMaterial() + "\nQuantidade: " + produto.getQuantidade() + "\nPreço: " + produto.getPreco() + "\nCategoria: " + produto.getCategoria() + "\nObservacoes: " + produto.getObservacoes());
                 }
             }
             
             else if(opcao.equals("Estoque")){
                 
                 Produto produto = buscarProduto();
                 
                 if (produto == null) {
                     JOptionPane.showMessageDialog(null, "Produto inválido! Item não cadastrado.");
                 } 
                 
                 else {
                     JOptionPane.showMessageDialog(null, "Dados do Estoque\nNome: " + produto.getNome() + "\nQuantidade: " + produto.getQuantidade());
                 }
             }
             
             txtNome.setText("");
        } 
           
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        telaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpcaoActionPerformed
        String opcao = cbOpcao.getSelectedItem().toString();
        if(opcao.equals("Cliente") || opcao.equals("Pedido") || opcao.equals("Agendamento") || opcao.equals("Venda") || opcao.equals("Pagamento") || opcao.equals("Entrega")){
            lbNome.setText("Digite o nome do cliente:");
        }
        else if(opcao.equals("Produto") || opcao.equals("Estoque")){
            lbNome.setText("Digite o nome do produto:");
        }
    }//GEN-LAST:event_cbOpcaoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbOpcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbNome;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
